---
- name: selinux check module
  ansible.builtin.command: semodule -l
  register: selinuxmodules
  check_mode: false
  changed_when: false
  when: zabbix_agent_selinux

- name: selinux copy modules
  ansible.builtin.copy:
    src: selinux/zabbix_agent.pp
    dest: /tmp/zabbix_agent.pp
    owner: root
    mode: 0600
  when: "selinuxmodules.stdout.find('zabbix_agent') == -1"

- name: selinux install module
  ansible.builtin.command: semodule -i /tmp/zabbix_agent.pp
  when: "selinuxmodules.stdout.find('zabbix_agent') == -1"
