---

- name: create facts.d directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    mode: 0755
    state: directory
    owner: root
    group: root

- name: create facts file
  ansible.builtin.template:
    src: facts.j2
    dest: /etc/ansible/facts.d/zabbix_agent.fact
    mode: 0644
    owner: root
    group: root
