---
- name: "Ensure zabbix agent started/stopped"
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    state: "{{ zabbix_agent_service_state }}"
    enabled: "{{ zabbix_agent_service_enabled }}"
  when: not zabbix_agent_test
