---
# tasks file for zabbix-agent

- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
    - "os-default.yml"
  tags:
    - always

- name: "Include package tasks"
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - zabbix-agent
        - zabbix-agent:package
  when: zabbix_agent_supprted
  tags:
    - always

- name: "Include selinux tasks"
  ansible.builtin.include_tasks:
    file: common-selinux.yml
    apply:
      tags:
        - zabbix-agent
        - zabbix-agent:selinux
  when: zabbix_agent_selinux and zabbix_agent_supprted
  tags:
    - always

- name: "Include config tasks"
  ansible.builtin.include_tasks:
    file: common-config.yml
    apply:
      tags:
        - zabbix-agent
        - zabbix-agent:config
  when: zabbix_agent_supprted
  tags:
    - always

- name: "Include sudo tasks"
  ansible.builtin.include_tasks:
    file: common-sudo.yml
    apply:
      tags:
        - zabbix-agent
        - zabbix-agent:sudo
  when: zabbix_agent_supprted
  tags:
    - always

- name: "Include facts tasks"
  ansible.builtin.include_tasks:
    file: common-facts.yml
    apply:
      tags:
        - zabbix-agent
        - zabbix-agent:facts
  when: zabbix_agent_supprted
  tags:
    - always

- name: "Include service tasks"
  ansible.builtin.include_tasks:
    file: common-service.yml
    apply:
      tags:
        - zabbix-agent
        - zabbix-agent:service
  when: zabbix_agent_supprted
  tags:
    - always
