---
# tasks file for zabbix-agent

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-default.yml"
  tags:
    - zabbix-agent
    - setup
    - config
    - service

# Debian  specific tasks
- include: setup-Debian.yml
  when: ansible_distribution in ('Debian', 'Ubuntu')

# CentOS  specific tasks
- include: setup-CentOS.yml
  when: ansible_distribution in ('CentOS', 'RedHat')

## Common setup tasks
- include: setup-common.yml

# Common configuration tasks tasks
- include: config.yml

# Common service tasks
- include: service.yml

# setup local facts
- include: facts.yml
