---
# tasks file for zabbix-agent
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - setup
    - config
    - repository
    - service
 
# Debian(setup)  specific tasks
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"

# RedHat(setup) specific tasks
- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"

# Common setup tasks
- include: setup.yml

# Common configuration tasks tasks
- include: config.yml

# Common service tasks
- include: service.yml
