---
# handlers file for zabbix-agent
- name: "restart zabbix-agent"        # noqa name[casing]
  ansible.builtin.service:
    name: "{{ zabbix_agent_service }}"
    state: restarted
  when: not zabbix_agent_test
