---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: debian-10
    image: debian:10
  - name: ubuntu-18.04
    image: ubuntu:18.04
  - name: centos-8
    image: centos:8
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: github
verifier:
  name: testinfra
  lint:
    name: flake8
